#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -plugin-tag package(ppx_driver.ocamlbuild)
                                     -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)    action lib-native ;;
        lib-byte)   $OCAMLBUILD bitcointalk.cma ;;
        lib-native) $OCAMLBUILD bitcointalk.cmxa btpump.native ;;
        test|tests) $OCAMLBUILD test/tests.otarget ;;
        doc)        shift; topkg doc --dev $* ;;
        api-doc)    shift; topkg doc $* ;;
        clean)      $OCAMLBUILD -clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
